### ISSUE TITLE
Missing "bin/a3m_to_feat" file to generate the features from a3m file

### ISSUE THREAD

**Issue by martinp7** [microsoft/Protein-Folding#2]
Hello the team, first of all thanks for the work!

I tried to run the example provided in the repository but I had an error since the file `bin/a3m_to_feat` is missing. The features can't be generated for the model.

Do you plan to add it in the repository to be able to run the example?

Thanks!

**Comment by fusong-ju** [comment]
This has been fixed in recent update.

Regards,
Fusong
